name: lint

on:
  push:
    paths:
      - 'applications/auth'
      - '.github/workflows/go-ci.yaml'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.0]
        golangci-lint-version: [v1.64.4]
    defaults:
      run:
        working-directory: applications/auth

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: applications/auth
          version: ${{ matrix.golangci-lint-version }}
          args: --timeout=5m

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests and generate JUnit report
        run: gotestsum --junitfile ../../report.xml --format testname -- ./...

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: report.xml

      - name: Report test results
        uses: dorny/test-reporter@v1
        with:
          name: Go Test Results
          path: report.xml
          reporter: jest-junit 
